# Generated by Django 4.2.3 on 2023-07-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
